# Generated by Django 3.1.2 on 2020-10-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_auto_20201025_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='family',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
