# Generated by Django 3.1.2 on 2020-10-26 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0006_remove_isoform_annotations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='isoform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.isoform'),
        ),
    ]
