# Generated by Django 3.1.2 on 2020-10-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0007_auto_20201026_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='condition',
            name='replicate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
