# Generated by Django 3.1.2 on 2020-10-26 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0008_auto_20201026_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organism',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='isoform',
            name='expression',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.expression'),
        ),
        migrations.AlterField(
            model_name='isoform',
            name='protein',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.protein'),
        ),
        migrations.AlterField(
            model_name='isoform',
            name='splicing',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='organism',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
