const UNVER = 0
const UNAUTH = 1
const TRYAUTH = 2
const ERRORAUTH = 3
const AUTHSUCESS = 4

export default {
    UNVERIFIED: UNVER,
    UNAUTHENTICATED: UNAUTH,
    TRYAUTH,
    ERRORAUTH,
    AUTHSUCCESS: AUTHSUCESS
}